sonar.projectKey=L01-GitFit_gitfit-app2
sonar.organization=l01-gitfit

sonar.projectName=gitfit-app
sonar.projectVersion=1.0.0

sonar.sources=app,components,store,utils
sonar.tests=__tests__
sonar.test.inclusions=**/__tests__/**/*.test.ts,**/__tests__/**/*.test.tsx

sonar.exclusions=**/node_modules/**,**/coverage/**,**/*.d.ts,**/assets/**,**/.expo/**,**/dist/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8